### ISSUE TITLE
Not working in shortcode product display

### ISSUE THREAD

**Issue by pacorocha** [woocommerce/woocommerce-subscriptions-custom-price-string#10]
The plugin works great, except it doesn't change the string when a product is displayed using shortcode, e.g. [product id="2"]

**Comment by bernattorras** [comment]
I can't replicate this issue as the custom price string is being displayed properly when the product is added via the [product] shortcode. 

If you're still able to replicate this issue using the latest version of the plugin, please add a comment and we'll continue our investigation from here. 

Thanks!
