### ISSUE TITLE
The most recent plugin version "1.0.3" still shows "1.0.1" when installed

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-subscriptions-custom-price-string#11]
When downloading and installing the latest plugin release `1.0.3` from https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string/releases, it still shows as version `1.0.1`:

![https://d.pr/i/XTv7Re](https://d.pr/i/XTv7Re+) 
Full Size: https://d.pr/i/XTv7Re

Because of the following string: https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string/blob/2b4bed0542ca6eb1f3d1130c143a41c79fda1037/woocommerce-subscriptions-custom-pricestring.php#L9

**Comment by bernattorras** [comment]
Thanks! Fixed.
