### ISSUE TITLE
Custom price string stays empty if edited for Variable products

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-subscriptions-custom-price-string#12]
## How to reproduce

1. Create a variable product and see that the default Custom price string is empty and shows the default value on the front-end:

![https://d.pr/i/19Klea](https://d.pr/i/19Klea+) 
Full Size: https://d.pr/i/19Klea

![https://d.pr/i/ikP9jw](https://d.pr/i/ikP9jw+) 
Full Size: https://d.pr/i/ikP9jw

2. Edit the default Custom price string to anything, the custom string replaces variation prices and doesn't show them at all now:

![https://d.pr/i/6jNZbT](https://d.pr/i/6jNZbT+) 
Full Size: https://d.pr/i/6jNZbT

![https://d.pr/i/5mg4NQ](https://d.pr/i/5mg4NQ+) 
Full Size: https://d.pr/i/5mg4NQ

3. Now empty the string back, it removes the default price from the product's page at all:

![https://d.pr/i/sZ13K7](https://d.pr/i/sZ13K7+) 
Full Size: https://d.pr/i/sZ13K7

![https://d.pr/i/xIhNs0](https://d.pr/i/xIhNs0+) 
Full Size: https://d.pr/i/xIhNs0

Now it doesn't even show the price if the variation is chosen:

![https://d.pr/i/w1akZ1](https://d.pr/i/w1akZ1+) 
Full Size: https://d.pr/i/w1akZ1

![https://d.pr/i/lGVvix](https://d.pr/i/lGVvix+) 
Full Size: https://d.pr/i/lGVvix

## Workaround

The only workaround I found is to completely remove these two meta_id:

![https://d.pr/i/cpuWqa](https://d.pr/i/cpuWqa+) 
Full Size: https://d.pr/i/cpuWqa

**Comment by SevenAcreFarm** [comment]
We are having the same/similar issue with variable products. We may or may not get the price listed on the catalog page, or the product page, but if edited then the price is just blank on both.

It appears as though the workaround above is valid... Every time you save a custom price on a variable product it creates duplicate database entries for that post_id, removing the "NULL" entry solves the problem.

https://i.imgur.com/atE8WPF.png

**Comment by bernattorras** [comment]
I can't replicate this issue. When I delete the contents of the "custom from string" field, the default from string is displayed as a placeholder and as the product from string in the Frontend. 

If you're still able to replicate this issue with the latest version of the plugin, please leave a comment and we'll continue our investigation from here! 

Thanks!
