### ISSUE TITLE
Custom from string auto-includes "/ month" text

### ISSUE THREAD

**Issue by SevenAcreFarm** [woocommerce/woocommerce-subscriptions-custom-price-string#14]
**When editing** the "custom from string" the result on the frontend is whatever you entered plus an added "/ month" text.

![Screen Shot 2020-06-08 at 2 47 04 PM](https://user-images.githubusercontent.com/63859031/84068590-2f7b7f80-a997-11ea-9b96-12ef20fe7492.png)
![Screen Shot 2020-06-08 at 2 49 33 PM](https://user-images.githubusercontent.com/63859031/84068652-4d48e480-a997-11ea-998e-48ce0203d543.png)

Editing this value, at any point in time, will cause [Issue #12](https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string/issues/12) to fire leaving you to edit the database every.single.time.

The frontend should display what you enter in the "custom from sting" field on the backend, and not add additional text stings.

**To reproduce** simply edit the "custom from string" and see that it adds "/ month" or equivalent automatically.

**Comment by bernattorras** [comment]
I can't replicate this issue. If you're still experiencing this problem with the latest version of the plugin, please reopen this issue and provide some screenshots of your product and a list with the exact steps that you're following to replicate it. 

Thanks!
