### ISSUE TITLE
1.0.3: Save Variations -> Warning: stripslashes() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce-subscriptions-custom-price-string#16]
I saved variations with nothing configured for custom price strings.

Traceback https://sentry.io/share/issue/529bd0d2bfd84cb4925fa482bb98803c/

Points to `save_custom_price_string()` and processing `$_REQUEST['_custom_price_string']`, with a `[ , , ]` value.

**Comment by bernattorras** [comment]
Fixed here: 01a256b484ae8b63f23b7dafd1fecc5110bcbc6c
