### ISSUE TITLE
WooCommerce Subscriptions - Custom price string is inactive. WooCommerce Subscriptions is required

### ISSUE THREAD

**Issue by Niklas-90** [woocommerce/woocommerce-subscriptions-custom-price-string#17]
Hello,

We would like to use this plugin. Regards to the description, the plugin should also support "Simple product" and "Variable product". However, we get the message that WooCommerce Subscription installation is needed.

> WooCommerce Subscriptions - Custom price string is inactive. This version of WooCommerce Subscriptions - Custom price string requires WooCommerce Subscriptions version 2.1 or newer. Please install or update WooCommerce Subscriptions to version 2.1 or newer »

Is there a way to change this, that this plugin also work without a WooCommerce Subscription installation?

**Comment by bernattorras** [comment]
I've created a new tag without the WooCommerce Subscriptions dependencies. 

You can download it from here: https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string/releases/tag/1.0.4-no_dependencies
