### ISSUE TITLE
Include the totals from the custom price string at checkout

### ISSUE THREAD

**Issue by marktmcgrath** [woocommerce/woocommerce-subscriptions-custom-price-string#19]
It would be great if we could extend the custom price string to the checkout page.

Currently, the checkout page shows the default string of the subscription which is confusing for folks who are signing up and may not be sure if they're charged on that last expiry date or not.

For example, by default the checkout will show something like: "$797.00 / month for 3 months". But if we could adjust that to something like "3 payments of $797". That might be a little more obvious.

**Comment by NickGreen** [comment]
Looks like this might be already filed and possible solution here: https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string/issues/2#issuecomment-700429279

**Comment by james-allan** [comment]
Closing as duplicate
