### ISSUE TITLE
Custom price string cannot be saved on Variable Subscriptions.

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-subscriptions-custom-price-string#22]
**Describe the issue**
Setting a custom 'From' price string on a variable subscription doesn't work - saving it results in the field being blank upon reload, and the from price isn't customized on the front-end. The custom price strings per-variation work just fine.

**Steps to replicate**
On WordPress 5.7.2 with only Storefront, WooCommerce, Subscriptions, and Subs Custom Price String active and up to date:

* Create a variable subscription product and at least one variation.
* Add a 'Custom From Price' at the top of the Variations tab.
* Save product. Observe error.
* Try again. Update product. Observe error.

**What should happen instead**
The custom price string should be saved and displayed as expected.

**Additional Information**

- User video demonstrating the issue: https://www.loom.com/share/c7295703791f4ed8a0b6c81a5f40dcf0
- From the video, I notice that the user has a custom 'From' string field in the 'advanced' tab, but I do not in mine. We both have version 1.0.4. It doesn't appear to work in either place for the user, but I couldn't replicate since i do not have the field in the 'Advanced' tab.
- There is a somewhat similar closed issue here, though that seemed to be about Variable Products, not Variable Subscriptions: 
- 4006187-zen

**Comment by melek** [comment]
Additionally, this seems related somewhat to issue #12 (though that looks like it was about Variable Products rather than Subscriptions).

#16 seems possibly related since it deals with the from price code, but I can't see why from the commit.

**Comment by Rypheal** [comment]
I face the same issue, the custom 'from price' is being reset on product save (variable subscription product type). Can someone please have a look into this?

Appreciate it a lot!

Or @melek : did you find a way to workaround this issue?

**Comment by Rypheal** [comment]
@bernattorras : could you perhaps have a look into this issue? Would be very appreciate it.

**Comment by fschmittlein** [comment]
@bernattorras : We have the same issue. Please, can you fix it?

**Comment by apostle-coffee** [comment]
Unfortunately this issue is happening for us too. On our Variable Subscription page the 'Custom from string' tab is visible and you can input this field, but when publishing/updating the page it vanishes and defaults back to the unwanted standard text. A fix for this would be great please!

**Comment by RidgeTek** [comment]
Same problem here - is there a resolution?

**Comment by wpniall** [comment]
Another report in 32581901-hc

**Comment by cmorillo** [comment]
Hi , I have managed to fix it. You have to change the code though:

```
/**
 * Save the custom price string in the current product's '_custom_price_string' meta
 *
 * @access public
 * @param mixed $post_id
 * @return void
 */
function save_custom_price_string( $post_id ) {
	if ( isset( $_REQUEST['_custom_price_string'] ) ) {

		// If it is coming from a variable subscription product, skip it (as we already use the woocommerce_save_product_variation hook for this purpose).
		if ( is_array( $_REQUEST['_custom_price_string'] ) ) {
			return;
		}

		$custom_price_string = wp_unslash( $_REQUEST['_custom_price_string'] );
		update_post_meta( $post_id, '_custom_price_string', $custom_price_string );

	}

	if ( isset( $_REQUEST['_custom_from_string'] ) ) {

		$custom_from_string = wp_unslash( $_REQUEST['_custom_from_string'] );
		update_post_meta( $post_id, '_custom_from_string', $custom_from_string );

	}
}
add_action( 'save_post', 'save_custom_price_string', 11 );

```

**Comment by RidgeTek** [comment]
Is this going to be updated in the next update?

**Comment by neilmccreadie** [comment]
Another report in 4554924-zen

**Comment by bernattorras** [comment]
Sorry for the delay! I've updated the plugin with a fix that should prevent this conflict! 

Please reopen the issue if the problem persits!

**Comment by fontaholic** [comment]
i added this fix to my site. although the input box appears on all products, it only works on those with variable Subscriptions. it would be nice if it worked with other variations and simple products as well.

**Comment by melek** [comment]
@fontaholic I like that idea; I think that opening a new issue would be the best way to suggest it, so it can be tracked separately.
