### ISSUE TITLE
Style the price

### ISSUE THREAD

**Issue by saltadmindev** [woocommerce/woocommerce-subscriptions-custom-price-string#6]
Hi, ive tried this plugin and its works perfectly but I cant target and style the price only from a string, example "From: £120 / for 6 months" input into your field in the product
Woocommerce separates the products pricing string into 4 different classes for styling , when using custom pricing string  it only uses the 1  "Price" class from Woocommerce classes. 
Will the ability to style the elements in a custom price string be added?

**Comment by jrick1229** [comment]
@saltadmindev - you can use a `<span>` within the custom price string input in the product's settings. This span will not be visible in the custom price string input after updating the product, but will be visible in the HTML on the frontend product page. This will allow you to separately customize each `<span>` element with CSS.
