### ISSUE TITLE
What string can I enter in order to reflect a "name your price" value?

### ISSUE THREAD

**Issue by jennykb** [woocommerce/woocommerce-subscriptions-custom-price-string#7]
One of my fields is a "name your price" field. Is there a string I can enter that will reflect whatever price a user enters in this field?

**Comment by bernattorras** [comment]
I'm not sure how are you adding this "name your price" field, but this feature isn't supported by the plugin, as it is only designed to overwrite the default "price string" or "from string" of the products with the values that you manually enter from the product editor page. 

If you want this field to dynamically display the price that the customer enters elsewhere, it would require some custom JavaScript or PHP code.
