### ISSUE TITLE
Product From String doesn't change

### ISSUE THREAD

**Issue by erikallkelly** [woocommerce/woocommerce-subscriptions-custom-price-string#9]
I have edited my product string multiple times and it only changed the first time I edited it and won't change from that.

lgbttakeover.com/trips/test-product

Then on another page, although I've changed the product string, it looks like I don't have the plugin enabled despite me adding custom text in this area. 

lgbttakeover.com/trips/barcelona

I have no problem with the custom price string.

**Comment by bernattorras** [comment]
I can't replicate this issue, as the custom from string gets properly saved and updated in the Frontend every time I change it from the backend.

If you're still able to replicate this issue using the latest version of the plugin, please add a comment and we'll continue our investigation from here.

Thanks!
